"""initial_schema

Revision ID: 690266d1dfe0
Revises: ea10c4fe9abe
Create Date: 2026-03-12 08:08:47.380575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690266d1dfe0'
down_revision: Union[str, None] = 'ea10c4fe9abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
