"""initial schema

Revision ID: ea10c4fe9abe
Revises: 
Create Date: 2026-03-11 20:39:08.854484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea10c4fe9abe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('crunchbase_id', sa.String(length=255), nullable=True),
    sa.Column('funding_stage', sa.String(length=50), nullable=True),
    sa.Column('total_raised', sa.BigInteger(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.SmallInteger(), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_saas', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crunchbase_id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_table('enrichment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_enrichment_cache_expires_at'), 'enrichment_cache', ['expires_at'], unique=False)
    op.create_table('recruiter_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=False),
    sa.Column('recruiter_slack_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_duplicate', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('hubspot_contact_id', sa.String(length=255), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('assigned_recruiter', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'company_id', name='uq_contact_email_company')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('scraped_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('board_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icp_score', sa.SmallInteger(), nullable=True),
    sa.Column('gtm_category', sa.String(length=50), nullable=True),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scraped_jobs_dedup', 'scraped_jobs', ['source_url', 'created_at'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_is_qualified'), 'scraped_jobs', ['is_qualified'], unique=False)
    op.create_index('ix_scraped_jobs_qualified', 'scraped_jobs', ['is_qualified', 'created_at'], unique=False)
    op.create_index(op.f('ix_scraped_jobs_source_url'), 'scraped_jobs', ['source_url'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=False),
    sa.Column('platform_lead_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hubspot_deal_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_message_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reply_type', sa.String(length=30), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('ooo_return_date', sa.Date(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_recruiter', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['outreach_message_id'], ['outreach_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_message_id')
    )
    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('suppressed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppression_list')
    op.drop_table('replies')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_scraped_jobs_source_url'), table_name='scraped_jobs')
    op.drop_index('ix_scraped_jobs_qualified', table_name='scraped_jobs')
    op.drop_index(op.f('ix_scraped_jobs_is_qualified'), table_name='scraped_jobs')
    op.drop_index('ix_scraped_jobs_dedup', table_name='scraped_jobs')
    op.drop_table('scraped_jobs')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('scrape_runs')
    op.drop_table('recruiter_assignments')
    op.drop_index(op.f('ix_enrichment_cache_expires_at'), table_name='enrichment_cache')
    op.drop_table('enrichment_cache')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
